// export const PAYMENT_PLAN_ADDRESS =
//   "0x7FbB81A636c2fC0351bd2Ec7213C53f69c67e431";
// export const PAYMENT_PLAN_ABI = [
//   {
//     inputs: [
//       { internalType: "address payable", name: "_seller", type: "address" },
//       { internalType: "address", name: "_arbiter", type: "address" },
//     ],
//     stateMutability: "nonpayable",
//     type: "constructor",
//   },
//   { inputs: [], name: "AllPaymentsReleased", type: "error" },
//   { inputs: [], name: "DirectPaymentsNotAllowed", type: "error" },
//   { inputs: [], name: "FailedToSendEther", type: "error" },
//   { inputs: [], name: "IncorrectFundingAmount", type: "error" },
//   { inputs: [], name: "InvalidAddresses", type: "error" },
//   { inputs: [], name: "InvalidAmounts", type: "error" },
//   { inputs: [], name: "InvalidRecipient", type: "error" },
//   { inputs: [], name: "NextReleaseTimeNotReached", type: "error" },
//   { anonymous: false, inputs: [], name: "ContractCompleted", type: "event" },
//   { anonymous: false, inputs: [], name: "ContractRefunded", type: "event" },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: "address",
//         name: "initiator",
//         type: "address",
//       },
//     ],
//     name: "DisputeRaised",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: "address",
//         name: "resolver",
//         type: "address",
//       },
//       {
//         indexed: false,
//         internalType: "address",
//         name: "recipient",
//         type: "address",
//       },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "DisputeResolved",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "FundReceived",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "PaymentReleased",
//     type: "event",
//   },
//   {
//     inputs: [],
//     name: "RELEASE_INTERVAL",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "amount",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "arbiter",
//     outputs: [{ internalType: "address", name: "", type: "address" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "currentState",
//     outputs: [
//       { internalType: "enum PaymentPlan.State", name: "", type: "uint8" },
//     ],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "fund",
//     outputs: [],
//     stateMutability: "payable",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "address", name: "buyers", type: "address" }],
//     name: "getBuyersAddress",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "getContractBalance",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "getContractUserBalance",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "nextReleaseTime",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "raiseDispute",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "refund",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "releaseAmount",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "releasePayment",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "releasedAmount",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address payable", name: "_recipient", type: "address" },
//     ],
//     name: "resolveDispute",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "seller",
//     outputs: [{ internalType: "address payable", name: "", type: "address" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "totalAmount",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   { stateMutability: "payable", type: "receive" },
// ];
// export const RATINGS_AND_REVIEWS_ADDRESS =
//   "0x15d37dEAE292cbefE23A7a544efa95350F141C13";
// export const RATINGS_AND_REVIEWS_ABI = [
//   {
//     inputs: [
//       { internalType: "address", name: "_rewardTokenAddress", type: "address" },
//     ],
//     stateMutability: "nonpayable",
//     type: "constructor",
//   },
//   { inputs: [], name: "AirdropToZeroAddress", type: "error" },
//   { inputs: [], name: "AmountMustBeGreaterThanZero", type: "error" },
//   { inputs: [], name: "DUPLICATE_REVIEW", type: "error" },
//   {
//     inputs: [
//       { internalType: "address", name: "spender", type: "address" },
//       { internalType: "uint256", name: "allowance", type: "uint256" },
//       { internalType: "uint256", name: "needed", type: "uint256" },
//     ],
//     name: "ERC20InsufficientAllowance",
//     type: "error",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "sender", type: "address" },
//       { internalType: "uint256", name: "balance", type: "uint256" },
//       { internalType: "uint256", name: "needed", type: "uint256" },
//     ],
//     name: "ERC20InsufficientBalance",
//     type: "error",
//   },
//   {
//     inputs: [{ internalType: "address", name: "approver", type: "address" }],
//     name: "ERC20InvalidApprover",
//     type: "error",
//   },
//   {
//     inputs: [{ internalType: "address", name: "receiver", type: "address" }],
//     name: "ERC20InvalidReceiver",
//     type: "error",
//   },
//   {
//     inputs: [{ internalType: "address", name: "sender", type: "address" }],
//     name: "ERC20InvalidSender",
//     type: "error",
//   },
//   {
//     inputs: [{ internalType: "address", name: "spender", type: "address" }],
//     name: "ERC20InvalidSpender",
//     type: "error",
//   },
//   { inputs: [], name: "NoRecipients", type: "error" },
//   { inputs: [], name: "TransferAmountExceedsAllowance", type: "error" },
//   { inputs: [], name: "TransferToZeroAddress", type: "error" },
//   { inputs: [], name: "YOU_HAVE_RECIEVED_A_TOKEN", type: "error" },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: "address",
//         name: "owner",
//         type: "address",
//       },
//       {
//         indexed: true,
//         internalType: "address",
//         name: "spender",
//         type: "address",
//       },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "value",
//         type: "uint256",
//       },
//     ],
//     name: "Approval",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: "address",
//         name: "owner",
//         type: "address",
//       },
//       {
//         indexed: true,
//         internalType: "address",
//         name: "spender",
//         type: "address",
//       },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "CustomApproval",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: "address", name: "from", type: "address" },
//       { indexed: true, internalType: "address", name: "to", type: "address" },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "CustomTransfer",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: "address",
//         name: "spender",
//         type: "address",
//       },
//       { indexed: true, internalType: "address", name: "from", type: "address" },
//       { indexed: true, internalType: "address", name: "to", type: "address" },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "CustomTransferFrom",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: "address", name: "user", type: "address" },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "penalty",
//         type: "uint256",
//       },
//     ],
//     name: "PenaltyApplied",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: "address", name: "user", type: "address" },
//       {
//         indexed: false,
//         internalType: "int256",
//         name: "change",
//         type: "int256",
//       },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "newScore",
//         type: "uint256",
//       },
//     ],
//     name: "ReputationChanged",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "reviewId",
//         type: "uint256",
//       },
//       {
//         indexed: false,
//         internalType: "address",
//         name: "reviewer",
//         type: "address",
//       },
//       {
//         indexed: false,
//         internalType: "address",
//         name: "serviceProvider",
//         type: "address",
//       },
//       { indexed: false, internalType: "uint8", name: "rating", type: "uint8" },
//     ],
//     name: "ReviewSubmitted",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: "address", name: "from", type: "address" },
//       {
//         indexed: false,
//         internalType: "address[]",
//         name: "recipients",
//         type: "address[]",
//       },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "TokensAirdropped",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: "address", name: "to", type: "address" },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "TokensMinted",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: "address", name: "user", type: "address" },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "amount",
//         type: "uint256",
//       },
//     ],
//     name: "TokensRewarded",
//     type: "event",
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: "address", name: "from", type: "address" },
//       { indexed: true, internalType: "address", name: "to", type: "address" },
//       {
//         indexed: false,
//         internalType: "uint256",
//         name: "value",
//         type: "uint256",
//       },
//     ],
//     name: "Transfer",
//     type: "event",
//   },
//   {
//     inputs: [],
//     name: "INITIAL_SUPPLY",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address[]", name: "recipients", type: "address[]" },
//       { internalType: "uint256", name: "amount", type: "uint256" },
//     ],
//     name: "airdrop",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "owner", type: "address" },
//       { internalType: "address", name: "spender", type: "address" },
//     ],
//     name: "allowance",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "_user", type: "address" },
//       { internalType: "uint256", name: "_penalty", type: "uint256" },
//     ],
//     name: "applyPenalty",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "spender", type: "address" },
//       { internalType: "uint256", name: "amount", type: "uint256" },
//     ],
//     name: "approve",
//     outputs: [{ internalType: "bool", name: "", type: "bool" }],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "address", name: "account", type: "address" }],
//     name: "balanceOf",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "decimals",
//     outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "_user", type: "address" },
//       { internalType: "uint256", name: "_amount", type: "uint256" },
//     ],
//     name: "decreaseReputationScore",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "uint256", name: "_reviewId", type: "uint256" }],
//     name: "deleteReview",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "_serviceProvider", type: "address" },
//     ],
//     name: "getAverageRating",
//     outputs: [{ internalType: "uint8", name: "averageRating", type: "uint8" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "address", name: "_user", type: "address" }],
//     name: "getPenaltyHistory",
//     outputs: [
//       { internalType: "uint256[]", name: "penalties", type: "uint256[]" },
//     ],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "uint256", name: "_reviewId", type: "uint256" }],
//     name: "getReview",
//     outputs: [
//       { internalType: "address", name: "reviewer", type: "address" },
//       { internalType: "address", name: "serviceProvider", type: "address" },
//       { internalType: "uint8", name: "rating", type: "uint8" },
//       { internalType: "string", name: "comment", type: "string" },
//       { internalType: "uint256", name: "timestamp", type: "uint256" },
//     ],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "getReviewCount",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "_serviceProvider", type: "address" },
//     ],
//     name: "getServiceProviderReviews",
//     outputs: [
//       { internalType: "uint256[]", name: "reviewIds", type: "uint256[]" },
//     ],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "address", name: "_user", type: "address" }],
//     name: "getTrustLevel",
//     outputs: [{ internalType: "string", name: "trustLevel", type: "string" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "", type: "address" },
//       { internalType: "uint256", name: "", type: "uint256" },
//     ],
//     name: "hasReviewed",
//     outputs: [{ internalType: "bool", name: "", type: "bool" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "", type: "address" },
//       { internalType: "address", name: "", type: "address" },
//     ],
//     name: "hasReviewedProvider",
//     outputs: [{ internalType: "bool", name: "", type: "bool" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "_user", type: "address" },
//       { internalType: "uint256", name: "_amount", type: "uint256" },
//     ],
//     name: "increaseReputationScore",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "address", name: "", type: "address" }],
//     name: "isBanned",
//     outputs: [{ internalType: "bool", name: "", type: "bool" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "mint",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "name",
//     outputs: [{ internalType: "string", name: "", type: "string" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "owner",
//     outputs: [{ internalType: "address", name: "", type: "address" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "reviewCount",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     name: "reviews",
//     outputs: [
//       { internalType: "address", name: "reviewer", type: "address" },
//       { internalType: "address", name: "serviceProvider", type: "address" },
//       { internalType: "uint8", name: "rating", type: "uint8" },
//       { internalType: "string", name: "comment", type: "string" },
//       { internalType: "uint256", name: "timestamp", type: "uint256" },
//     ],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "rewardAmount",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "rewardToken",
//     outputs: [{ internalType: "contract CueToken", name: "", type: "address" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "", type: "address" },
//       { internalType: "uint256", name: "", type: "uint256" },
//     ],
//     name: "serviceProviderReviews",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
//     name: "setRewardAmount",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "_serviceProvider", type: "address" },
//       { internalType: "uint8", name: "_rating", type: "uint8" },
//       { internalType: "string", name: "_comment", type: "string" },
//     ],
//     name: "submitReview",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "symbol",
//     outputs: [{ internalType: "string", name: "", type: "string" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "totalSupply",
//     outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
//     stateMutability: "view",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "to", type: "address" },
//       { internalType: "uint256", name: "amount", type: "uint256" },
//     ],
//     name: "transfer",
//     outputs: [{ internalType: "bool", name: "", type: "bool" }],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [
//       { internalType: "address", name: "from", type: "address" },
//       { internalType: "address", name: "to", type: "address" },
//       { internalType: "uint256", name: "amount", type: "uint256" },
//     ],
//     name: "transferFrom",
//     outputs: [{ internalType: "bool", name: "", type: "bool" }],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [],
//     name: "transferTokensWhenSignedUp",
//     outputs: [],
//     stateMutability: "nonpayable",
//     type: "function",
//   },
//   {
//     inputs: [{ internalType: "address", name: "", type: "address" }],
//     name: "userReputations",
//     outputs: [
//       { internalType: "uint256", name: "score", type: "uint256" },
//       { internalType: "uint256", name: "reviewCount", type: "uint256" },
//     ],
//     stateMutability: "view",
//     type: "function",
//   },
// ];